version: 1
disable_existing_loggers: true

formatters:
  brief: 
    format: '%(name)s - %(levelname)s - %(message)s'
  precise: 
    format: '%(asctime)s - %(name)s %(levelname)s - %(message)s'

handlers:
  console:
    class : logging.StreamHandler
    formatter: brief
    stream  : ext://sys.stdout
  file:
    class : logging.handlers.RotatingFileHandler
    formatter: precise
    filename: ./logs/jsplog.log
    encoding: utf-8
    maxBytes: 120000
    backupCount: 3
loggers:
  mhp:
    level: INFO  
    handlers: [console]
    propagate: no 
root:
  level: INFO  # DEBUG INFO ERROR
  handlers: [console]
